name: Release Contrib

on:
  push:
    tags: ["v*"]

jobs:
  release:
    name: Release Contrib
    uses: ./.github/workflows/base-release.yaml
    with:
      distribution: otelcol-contrib
      goos: '[ "linux", "darwin" ]'
      goarch: '[ "386", "amd64", "arm64", "ppc64le", "arm", "s390x", "riscv64" ]'
      nightly: ${{ contains(github.ref, '-nightly') }}
    secrets: inherit
    permissions: write-all
